### PR TITLE
Add LinkedIn OpenID Socialite provider

### PR DESCRIPTION
**Pull request by thecrazybob**
Refer to:

- https://github.com/laravel/socialite/pull/662
- https://laravel.com/docs/10.x/socialite#configuration

### CODE REVIEW

**Comment by andrewdwallo** [comment]
Thanks! One more thing before I merge. Would it be better to just use the display name "LinkedIn" instead of "LinkedIn OpenID" for both?

**Comment by andrewdwallo** [comment]
Also, I suppose we should update `composer.json` to use `"laravel/socialite": "^5.9"` as well?

**Comment by thecrazybob** [comment]
Thanks for pointing out the version change in composer. I have bumped it to `^5.9` and renamed the provider to just `LinkedIn`

**Comment by andrewdwallo** [comment]
Thanks! I will be adding Slack as well soon. Thinking I will update the Twitter logo and name as well.

**Pull request merged**
