### PR TITLE
Add Arabic Language

### PR DESCRIPTION
**Pull request by mstfkhazaal**
I added the Arabic language and fixed the views (RTL)

But I couldn't change the language of the roles (FilamentCompaniesServiceProvider) of the session only if the default language of the project is changed because the service provider can't access the request session

Like if i saved the locale in session not get the correct language in provider
image

But if  change locale from config/app.php
image
image

Read this:
https://github.com/laravel/framework/discussions/46706

### CODE REVIEW

**Comment by andrewdwallo** [comment]
Language for the roles should just be changed by the developer anyway so that's fine. I will look at this when I get back home.

**Comment by andrewdwallo** [comment]
> I added the Arabic language and fixed the views (RTL)
> 
> But I couldn't change the language of the roles (FilamentCompaniesServiceProvider) of the session only if the default language of the project is changed because the service provider can't access the request session

**I have a few things that need to be taken care of before I consider merging this:**

1. I will not merge this if you do not fix your commits. One of your commits is "Added French Language". What you added is not French, it is English. If you are not going to add French, then either delete it or I will. 
2. Remove what you have committed in the view files. I am currently fixing the design in my current branch that will be committed.
3. Remove the locale for roles that you committed in the Service Provider and the lang files. Locale should not be added there and the reason why there is a service provider file in the first place is so that it can be edited by the developer who installs it.

**Comment by mstfkhazaal** [comment]
now>?

**Comment by andrewdwallo** [comment]
Thank you

**Pull request merged**
