### PR TITLE
fix static panel id in login

### PR DESCRIPTION
**Pull request by atmonshi**
still a wip

### CODE REVIEW

**Comment by andrewdwallo** [comment]
@atmonshi Is this still a WIP?

**Comment by atmonshi** [comment]
no it's ready 👍

**Comment by andrewdwallo** [comment]
@atmonshi It still needs more work before I merge. Have you tried to go to the Register page yet?

**Comment by andrewdwallo** [comment]
The socialite component is used in the Register view as well. Terms and Privacy policy routes need to change in the register page, etc.

**Comment by atmonshi** [comment]
refactor and fix other places for the static route call
only left: `connected-accounts-form.blade.php` since I don't have any idea how to fix it

**Comment by andrewdwallo** [comment]
Is it possible that for the Register page for the Terms and Privacy Policy routes to instead use the `getRouteName()` method inside those pages?

**Comment by andrewdwallo** [comment]
In the PrivacyPolicy page do this:
```php
public static function getSlug(): string
{
    return 'privacy-policy';
}

public static function getRouteName(?string $panel = null): string
{
    $panel ??= Filament::getCurrentPanel()?->getId();

    return (string) str(static::getSlug())
        ->replace('/', '.')
        ->prepend("filament.{$panel}.auth.");
}
```

In the Terms page:
```php
public static function getSlug(): string
{
    return 'terms-of-service';
}

public static function getRouteName(?string $panel = null): string
{
    $panel ??= Filament::getCurrentPanel()?->getId();

    return (string) str(static::getSlug())
        ->replace('/', '.')
        ->prepend("filament.{$panel}.auth.");
}
```

In `routes\web.php`:
```php
Route::name('filament.')
    ->group(static function () {
        foreach (Filament::getPanels() as $panel) {
            $hasPlugin = $panel->hasPlugin('companies');

            if (!$hasPlugin) {
                continue;
            }

            $panelId = $panel->getId();
            $domains = $panel->getDomains();
            $plugin = $panel->getPlugin('companies');

            foreach ((empty($domains) ? [null] : $domains) as $domain) {
                Route::domain($domain)
                    ->middleware($panel->getMiddleware())
                    ->name("{$panelId}.")
                    ->prefix($panel->getPath())
                    ->group(static function () use ($plugin, $panel) {
                        $oauth_route = '/oauth/{provider}';
                        $oauth_callback_route = '/oauth/{provider}/callback';

                        if (Socialite::hasSocialiteFeatures() && $plugin->socialite()) {
                            Route::get($oauth_route, [OAuthController::class, 'redirectToProvider'])->name('oauth.redirect');
                            Route::get($oauth_callback_route, [OAuthController::class, 'handleProviderCallback'])->name('oauth.callback');
                        }

                        Route::name('auth.')->group(static function () use ($plugin, $panel): void {
                            if (Features::hasTermsAndPrivacyPolicyFeature() && $plugin->termsAndPrivacyPolicy()) {
                                Terms::routes($panel);
                                PrivacyPolicy::routes($panel);
                            }
                        });

                        $company_invitations_route = '/company-invitations/{invitation}';

                        // Companies...
                        if (Features::hasCompanyFeatures() && $plugin->companies(invitations: true)) {
                            Route::get($company_invitations_route, [CompanyInvitationController::class, 'accept'])
                                ->middleware(['signed'])
                                ->name('company-invitations.accept');
                        }
                    });
            }
        }
    });
```

**Comment by andrewdwallo** [comment]
Also in Register page:
```php
protected function getTermsFormComponent(): Component
{
    return Checkbox::make('terms')
        ->label(new HtmlString(__('filament-companies::default.subheadings.auth.register', [
            'terms_of_service' => '<a target="_blank" href="'.route(Terms::getRouteName()).'" class="font-medium outline-none hover:underline focus:underline text-primary-600 hover:text-primary-500 dark:text-primary-500 dark:hover:text-primary-400">'.__('filament-companies::default.links.terms_of_service').'</a>',
            'privacy_policy' => '<a target="_blank" href="'.route(PrivacyPolicy::getRouteName()).'" class="font-medium outline-none hover:underline focus:underline text-primary-600 hover:text-primary-500 dark:text-primary-500 dark:hover:text-primary-400">'.__('filament-companies::default.links.privacy_policy').'</a>',
        ])))
        ->validationAttribute('Terms of Service and Privacy Policy')
        ->accepted();
}
```

**Comment by andrewdwallo** [comment]
I can update it myself if needed. I would also rather not have the method to get the panelId within the Socialite class. It is meant for only Socialite specific methods.

**Comment by atmonshi** [comment]
np, pushed the updates.

**Comment by andrewdwallo** [comment]
Okay thanks! Will edit some things, make sure all is good and merge.

**Comment by andrewdwallo** [comment]
Just let me know when you are completely finished.

**Comment by atmonshi** [comment]
ok, I wanted to make separate PR for each thing, but they all tied together, so it had to be one big PR :)

add laravel pint to clean up the code. and a github action.
support RTL directions.
another fix in `routes/web.php` for static `company`

**Comment by andrewdwallo** [comment]
@atmonshi You need to thoroughly test and make sure that everything works correctly after you are finished. I was okay with everything else but adding Pint was a little over the line. It's okay and I will accept it, but make sure that Pint didn't remove nullable parameters/arguments that were meant to be nullable. If a user doesn't provide an argument for a feature that they do not want, there shouldn't be any errors thrown. It was designed to be like this so that the user doesn't have to provide every argument.

**Comment by atmonshi** [comment]
@andrewdwallo  Nothing has been removed nullable wais...

Pint improves things like:
`array|null $features = null`
to
`array $features = null`
still nullable but `|null` is unnecessary  :)

I am using the default profile from laravel and using it in my zeus packages, too.

I've been using this branch locally heavily for the past two days, changed and tested a lot of options, and so far, no issues 👍

**Comment by andrewdwallo** [comment]
How is that an improvement though? Sometimes using `array|null $features = null`, for example, makes the code more explicit, enforces strict types, improves IDE autocompletion and type checking, provides clarity, and leaves no room for ambiguity.

**Comment by atmonshi** [comment]
🤷🏽‍♂️ 😄 
you have to ask the `php-cs-fixer` team

I can rework it all and remove `pint` if you want, can take me a few days.
for now, I still can use my fork in the app I am working on.

**Comment by andrewdwallo** [comment]
Don't worry about it. I just don't agree that it is an improvement though was all I was saying.

**Comment by andrewdwallo** [comment]
Yeah, never mind. Sorry but I don't want to remove the nullable types. I don't think it is an improvement, so if you are planning on still making this PR, I need you to revert what Pint did, but I am still okay with Pint being added to the plugin. After reverting what Pint did, create a `pint.json` file and add this rule to it:

```json
{
    "preset": "laravel",
    "rules": {
        "nullable_type_declaration_for_default_null_value": {
            "use_nullable_type_declaration": true
        },
    }
}
```

The Laravel preset for Pint sets the value for this rule to false, which is reason why nullable type declarations were removed, which is what I do not want.

**Comment by atmonshi** [comment]
it doesn't remove nullable types
there is **NO** difference between:

`?string;` and `string|null`

Human, IDES, and other code analytics tools will still know it's nullable.

I reverted `pint`, and this PR will include the fix for dynamic routes and the RTL support.

You can add pint with any preset and configuration you need :) sorry I don't have more time to do more chores.

**Comment by andrewdwallo** [comment]
I am referencing exactly what you said earlier here.

> @andrewdwallo Nothing has been removed nullable wise...
> 
> Pint improves things like: `array|null $features = null` to `array $features = null` still nullable but `|null` is unnecessary :)
> 
> I am using the default profile from laravel and using it in my zeus packages, too.
> 
> I've been using this branch locally heavily for the past two days, changed and tested a lot of options, and so far, no issues 👍

What you just said which is, "There is no difference between `?string;` and `string|null`", is simply not the same thing you said earlier. Yes, I know there is no difference between using `?string` and `string|null`, I'm not dumb. The rule I said to use in pint simply just changes everything from `string|null` to `?string`, which is the newer syntax.

Regarding what you said earlier, there is a difference between `?string $var = null` and `string $var = null`.

`?string $var = null`:
This syntax means that $var can be either of type string or null. It explicitly specifies that null is an acceptable value. The other does not.

**Comment by andrewdwallo** [comment]
Sorry if you thought that was a chore though. It is fine, I will add pint later if need be.

**Pull request closed without merging**
