### PR TITLE
Employee Invitation: Using alpine js for role selection

### PR DESCRIPTION
**Pull request by margarizaldi**
In my opinion, using livewire for updating visual appearance is not necessary, so using alpine must be better.

### CODE REVIEW

**Comment by andrewdwallo** [comment]
> In my opinion, using livewire for updating visual appearance is not necessary, so using alpine must be better.

Works great! I need to learn more alpine to be honest. Is there anything that needs to be updated in either the corresponding Action classes or the `CompanyEmployeeManager.php` Livewire component file? Will this affect any validation?

Also, if you are adding alpine here, might as well apply the same to the modal when editing a user's current role correct?

**Comment by margarizaldi** [comment]
> Is there anything that needs to be updated in either the corresponding Action classes or the `CompanyEmployeeManager.php` Livewire component file? Will this affect any validation?
> 
I think there's nothing to do with the component. I just moved the DOM related task from the server to the browser. And the validation is still there, no touch.

> Also, if you are adding alpine here, might as well apply the same to the modal when editing a user's current role correct?
>
Maybe tonight if I can I'll try....

**Comment by andrewdwallo** [comment]
Sounds good, thanks! I already edited it in my current branch for the modal and works. Will wait on you.

**Comment by margarizaldi** [comment]
> Sounds good, thanks! I already edited it in my current branch for the modal and works. Will wait on you.
>
Hi sorry for my late response... And it's great to know that everything works... Thank you!

**Pull request merged**
